name: Build Windows

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: 'stable'
          cache: true

      - name: Add Windows platform support
        run: flutter create . --platforms=windows

      - name: Setup Visual Studio
        uses: microsoft/setup-msbuild@v2

      - name: Enable Windows desktop support
        run: flutter config --enable-windows-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows release
        run: flutter build windows --release --verbose

      - name: Upload Windows build artifact
        uses: actions/upload-artifact@v4
        with:
          name: BirdQuiz-Windows
          path: build/windows/x64/runner/Release/
